#!/bin/bash

# Shortcuts
alias c='clear'
alias ll='ls -alF'
alias ..='cd ..'
alias rg='rg --color=auto'

# Git aliases
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gs='git status'
alias gl='git log --oneline --decorate --graph'
alias gp='git push'
alias gpl='git pull'
alias gb='git branch'
alias gd='git diff'
alias gds='git diff --staged'

# Additional aliases
alias la='ls -lAh'
alias l='ls -CF'
alias h='history'
alias cdp='cd ~/Projects'
alias dt='cd ~/Desktop'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias findf='find . -type f -name'
alias findd='find . -type d -name'

# Curl aliases
alias ip='curl ifconfig.io'
alias weather='curl wttr.in'

# Ping aliases
alias ping='sudo ping -c 5'

# Netstat aliases
alias ports='sudo netstat -tulanp'

# Docker aliases
alias dps='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dimages='docker images --format "{{.Repository}}\t{{.Tag}}\t{{.Size}}"'
alias dclean='docker system prune -af'

# Utility aliases
alias clock='while sleep 1; do clear; echo -n "$(date +%T)"; done'
alias calc='bc -l'
alias now='date +"%Y-%m-%d %H:%M:%S"'
alias startworkday='source ~/bin/start_workday.sh'
alias docs='cd $HOME/Documents'
alias proj='cd $HOME/Projects'

# GitHub CLI

if gh extension list | grep -q 'github/gh-copilot'; then
  copilot_shell_suggest() {
    gh copilot suggest -t shell "$@"
  }
  alias '??'='copilot_shell_suggest'

  # Function to handle Git command suggestions
  copilot_git_suggest() {
    gh copilot suggest -t git "$@"
  }
  alias 'git?'='copilot_git_suggest'

  # Function to handle GitHub CLI command suggestions
  copilot_gh_suggest() {
    gh copilot suggest -t gh "$@"
  }
  alias 'gh?'='copilot_gh_suggest'
fi

# PNPM

alias pn=pnpm

