# Font Configuration
font_family             JetBrains Mono
font_size               12.0
symbol_map              U+E100-U+E16F JetBrains Mono

# Appearance
background_opacity      0.9
window_padding_width    12.00
inactive_text_alpha     0.6
cursor_shape            block
cursor_blink_interval   0.5
tab_bar_style           powerline

# Behavior
copy_on_select          yes
scrollback_lines        10000
enabled_layouts         tall,stack,splits

# Theme & Includes
include                 current-theme.conf